### ISSUE TITLE
Build errors in terraform tenant pipeline

### ISSUE THREAD

**Issue by NissesSenap** [XenitAB/azure-devops-templates#141]
I can't see this error in our XKS pipelines but for one tenant I can see it.
When I run make locally on my computer it works without any issues.

```shell
Digest: sha256:5ee2e1d098e1228e7c49387b9cf570f567b662237ba289a11b7d926fcc1d1849
Status: Downloaded newer image for ghcr.io/xenitab/github-actions/tools:2022.10.1
[Errno 13] Permission denied: '/work/.azure/versionCheck.json'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/cloud.py", line 474, in get_active_cloud_name
    return cli_ctx.config.get('cloud', 'name')
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 99, in get
    raise last_ex  # pylint:disable=raising-bad-type
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 94, in get
    return config.get(section, option)
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 208, in get
    return self.config_parser.get(section, option)
  File "/opt/az/lib/python3.10/configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "/opt/az/lib/python3.10/configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'cloud'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/az/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/__main__.py", line 38, in <module>
    az_cli = get_default_cli()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 910, in get_default_cli
    return AzCli(cli_name='az',
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/__init__.py", line 86, in __init__
    self.cloud = get_active_cloud(self)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/cloud.py", line 555, in get_active_cloud
    return get_cloud(cli_ctx, get_active_cloud_name(cli_ctx))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/cloud.py", line 477, in get_active_cloud_name
    _set_active_cloud(cli_ctx, default_cloud_name)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/cloud.py", line 468, in _set_active_cloud
    cli_ctx.config.set_value('cloud', 'name', cloud_name)
  File "/opt/az/lib/python3.10/site-packages/knack/config.py", line 161, in set_value
```

Could the following be something to look in to?

https://learn.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-file

```shell
environment {
    AZURE_CONFIG_DIR = "${env.WORKSPACE}/.azure"
}
```

**Comment by NissesSenap** [comment]
This is not a problem, i was using a old template version and was why i got the issue.
